development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: shopqi_db
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: shopqi_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: shopqi_production
  pool: 5
  username: postgres
  password: postgres 